root: true

globals:
  node: true
  jest: true
  jest/globals: true

# no import keyword errors
parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"
  - jest

extends:
  - eslint:recommended
  # not all ESLint core rules are compatible with TypeScript,
  # so you need to add both eslint:recommended and
  # plugin:@typescript-eslint/eslint-recommended (which will adjust
  # the one from ESLint appropriately for TypeScript) to your config
  - plugin:@typescript-eslint/eslint-recommended
  # gets rid of "Parsing error: ImportDeclaration should appear
  # when the mode is ES6 and in the module context" error
  - plugin:@typescript-eslint/recommended
  # all rules were off by default
  - plugin:import/typescript
  # enforces good testing practices
  - plugin:jest/recommended
  # adds some stylistic rules, such as prefer-to-be-null,
  # which enforces usage of toBeNull over toBe(null)
  - plugin:jest/style

rules:
  semi: 0
  # stupid rule
  "@typescript-eslint/explicit-function-return-type": off
  # must be turned off for typescript version to work
  no-unused-expressions": off
  # better version of no-undef with optional chaining support
  "@typescript-eslint/no-unused-expressions": error
  # no semi-colons needed in types
  "@typescript-eslint/member-delimiter-style": off
  "@typescript-eslint/ban-ts-ignore": off
  "@typescript-eslint/camelcase": off
  # allow use of the non-null assertion operator
  "@typescript-eslint/no-non-null-assertion": off
