# In general the pattern mostly looks like this:
# type(scope?): subject  #scope is optional

# a type can be:
# build, ci, chore, docs, feat, fix, perf, refactor, revert, style, test
#  ✔,   ✔,   ✔,    ✔,    ✔,   ✔,   ?,      ✔,      ✔,      ?,    ✔

# Real world examples can look like this:
# chore: run tests on travis ci
# fix(server): send cors headers
# feat(blog): add comment section

# The most common commit conventions follow this pattern:
# type(scope?): subject
# body?
# footer?

extends:
  - "@commitlint/config-conventional"
