export { SplashPage } from "./splash-page"
export { DashboardPage } from "./dashboard"
export { RegisterPage } from "./register-page"
export { LoginPage } from "./login-page"
export { NotFoundPage } from "./not-found"
