export { SplashPage } from './splash-page'
export { DashboardPage } from './dashboard-page'
export { RegisterPage } from './register-page'
export { LoginPage } from './login-page'
export { NotFoundPage } from './not-found'
